
server:
  port: 8181


spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/jpa
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    # show-sql: true  # ?? ??? ??? ???? ??
    # ??? ?? ? ?? ??? ?? ???? ??
    database-platform: org.hibernate.dialect.MariaDB106Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true # sql? ????? ??? ??
    database: mysql # ?? ?? ??
  servlet:
   multipart:
     max-file-size: 10MB #1개 파일의 최대 사이즈
     max-request-size: 20MB #전체 요청의 최대 사이즈
logging.level:
  org.hibernate.SQL: debug

# swagger setting
springdoc:
  swagger-ui:
    path: /myapi.html
#보안을 위해 yml 파일에 저장
jwt:
  secret: 5iUUmWK1gNrcI5maX2MHsWnoTmn1HTfoFqPLfsNUw77yYyZbZjl0oujJFBRQ1yK6kMFXIfgV3t/BXsjd5yW8jQ==

#업로드 파일 저장 경로
upload:
  path: D:/todo_upload
